// Generated by gencpp from file ball_chaser/GoToTarget.msg
// DO NOT EDIT!


#ifndef BALL_CHASER_MESSAGE_GOTOTARGET_H
#define BALL_CHASER_MESSAGE_GOTOTARGET_H

#include <ros/service_traits.h>


#include <ball_chaser/GoToTargetRequest.h>
#include <ball_chaser/GoToTargetResponse.h>


namespace ball_chaser
{

struct GoToTarget
{

typedef GoToTargetRequest Request;
typedef GoToTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoToTarget
} // namespace ball_chaser


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ball_chaser::GoToTarget > {
  static const char* value()
  {
    return "c8652349d2a34a90a09475339e2a93d9";
  }

  static const char* value(const ::ball_chaser::GoToTarget&) { return value(); }
};

template<>
struct DataType< ::ball_chaser::GoToTarget > {
  static const char* value()
  {
    return "ball_chaser/GoToTarget";
  }

  static const char* value(const ::ball_chaser::GoToTarget&) { return value(); }
};


// service_traits::MD5Sum< ::ball_chaser::GoToTargetRequest> should match 
// service_traits::MD5Sum< ::ball_chaser::GoToTarget > 
template<>
struct MD5Sum< ::ball_chaser::GoToTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ball_chaser::GoToTarget >::value();
  }
  static const char* value(const ::ball_chaser::GoToTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ball_chaser::GoToTargetRequest> should match 
// service_traits::DataType< ::ball_chaser::GoToTarget > 
template<>
struct DataType< ::ball_chaser::GoToTargetRequest>
{
  static const char* value()
  {
    return DataType< ::ball_chaser::GoToTarget >::value();
  }
  static const char* value(const ::ball_chaser::GoToTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ball_chaser::GoToTargetResponse> should match 
// service_traits::MD5Sum< ::ball_chaser::GoToTarget > 
template<>
struct MD5Sum< ::ball_chaser::GoToTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ball_chaser::GoToTarget >::value();
  }
  static const char* value(const ::ball_chaser::GoToTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ball_chaser::GoToTargetResponse> should match 
// service_traits::DataType< ::ball_chaser::GoToTarget > 
template<>
struct DataType< ::ball_chaser::GoToTargetResponse>
{
  static const char* value()
  {
    return DataType< ::ball_chaser::GoToTarget >::value();
  }
  static const char* value(const ::ball_chaser::GoToTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BALL_CHASER_MESSAGE_GOTOTARGET_H
